- main.c
- src/mos.h
This suppresses error reporting on processing the autoexec.txt file if the file is not present, as it's OK to _not_ have that file. :grin:
All other errors on attempting to process that file _will_ be shown, so booting a machine with no SD card present will show "SD card failure".  I had been tempted to suppress that error too, but keeping it feels more sensible given that in normal use users should have an SD card inserted.
> hide error when there is no autoexec.txt file

- main.c
- src/version.h
move version info out to `version.h` file
version info now a semantic version, with major, minor, patch, and “candidate” info, as well as an indicator for candidate type (displayed if candidate number is non-zero)
support for showing an automatically-generated build number added, which can be provided by a build script and is intended to be derived from the git hash
with this approach it should also be possible in the future to add other tooling to automatically increment version numbers
version info also includes the codebase variant, allowing us to easily differentiate between Quark and Console8
> Semantic versioning

- main.c
- src/mos.c
- src/mos_editor.c
- src/mos_editor.h
- src_startup/globals.asm
Building on work done by @HeathenUK in #11 this adds a few enhancements
brief summary of changed/enhanced functionality:
if you are at the start of a line and press up, it will go to the previous history item if there is one, otherwise do nothing
if you are somewhere along a line and press up it will either go up a line within the current string or if you’re already at the top line of that string go to the beginning
if you are at the end of a line and press down it will go to the next history item if there is one, otherwise do nothing
if you are somewhere along a line and press down it will either go down a line within the current string, or if you’re already on the bottom line go to the end
you’re always left at the end of a line when moving position in history - this means that you’ll …
> Command history (slightly enhanced)

- README.md
- main.c
- src/defines.h
- src/mos.c
- src/mos.h
- src/mos_api.asm
- src/mos_editor.c
- src/mos_editor.h
- src/strings.c
- src/strings.h
- src/version.h
- src_fatfs/ff.c
- src_fatfs/ff.h
- src_fatfs/ffconf.h
Incorporates _most_ of the changes from the "rainbow" MOS that @tomm has been experimenting with
To briefly summarise, that includes:
* changes/fixes from @breakintoprogram (added to the Quark codebase since 1.04 - currently unreleased)
* "comment" commands from @sadbeast
* enhanced VDU command from @HeathenUK 
* tab command completion from @HeathenUK 
* hotkey support from @HeathenUK
* support for a `bin` directory from @HeathenUK 
* directory listing enhancements from @tomm 
Also includes:
* some minor fixes
* smarter "help" command
* confirmation step for wild-card delete
* line editor now supports flags to control whether tab-completion, hotkeys and history are enabled
The current intent is that this will form the basis of a new 2.2.0 MOS release
> Rainbow neu

- src/mos.c
- src/mos_editor.c
- src/version.h
the 2.2.0 release included a significant bug in copy which could cause screen corruption.  additionally it was found that copy could only copy files to a separate (different) destination directory, rather than to an explicit filename
directory listing was found to be not functional on a freshly booted machine that booted into ADL BASIC
additionally directory listing would show no output at all when an empty directory was found, and could also show only partial output if a `malloc` had failed
this PR addresses all of theses issues
> fix issues around copy and dir

- src/mos_api.inc
**Fixes missing colon**
A missing colon was identified on line 126 of `mos_api.inc` after the the declaration of the `ffs_fdisk` equate.
This pull request addresses build failures when including `src/mos_api.inc` in projects caused by the missing colon. No other changes have been made. Adding the colon resolves the syntax error and allows build that include `src/mos_api.inc` to complete successfully.
The agon-mos project itself does not use `src/mos_api.inc` when building, so this syntax does not break the build of this project, it only breaks builds of projects that include `src/mos_api.inc`.
This fix should ensure smoother integration of the file in projects.
> chore(): add missing colon

- main.c
- src/mos_editor.c
- src/mos_editor.h
Changes how CLI history is recorded, moving it from a static fixed length array of chars to storing pointers to variable length strings in the heap
Duplicate history items are no longer pushed, altho this check is only against the most recent history entry
This gives us a chunk more heap space
> Move CLI history into the heap

- src/mos.c
these are mostly removals of unused variables, and a removal of a `goto`
these had been raised as PRs #61, #62, #63, #64, and #65
one or two other unused variables also spotted along the way and removed
> reproduce envenomator’s tidyings of mos.c

- src/defines.h
- src/mos.c
- src/mos_editor.c
- src/strings.c
Bumps up stack space to 2kb, fixing an issue observed with the `copy` command causing crashes from the MOS CLI
Fixes an issue observed with `echo` where `|!` token wasn't being correctly interpreted
Fixes #87 where history could slightly misbehave when not pushing a new item
> Fix issues discovered in 2.3.0

- src/mos.c
- src/mos.h
- src/mos_sysvars.c
adds new `RunFile` and `LoadFile` commands which look up a system variable named `Alias$@RunType_<extension>` or `Alias$@LoadType_<extension>` to find a command to run or load a file
in a future update the CLI will be updated to automatically use runtypes to attempt to run commands
some preliminary system variables for several load types and run types have been added.  for instance, `Alias$@RunType_bin` is defined to do `RunBin %*0`, and `Alias$@RunType_bbc` is `BBCBasic %*0`
Closes #78
> implement runtypes and loadtypes

- src/mos.c
these got accidentally broken when double-quotes around arguments support was added - oops!
> fix aliases

- main.c
- src/defines.h
- src/serial.asm
- src/uart.c
sets up UART0 to do both RTS and CTS
`wait_ESP32` now does a pure wait, with no timeout, as an Agon can’t operate without a working VDP, and the VDP hasn’t supported the lower baud rate in forever.
on successful receipt of a “general poll” response it now sends a "set feature flag" command to switch the VDP to use full duplex comms
from experimentation it seems that MOS doesn’t actually really need to care whether the VDP _actually_ switches over to full-duplex mode or not - it will carry on working regardless, therefore no checking is done to verify the switch has happened
includes a fix to `UART1_serial_GETCH` which was looking at the incorrect flag bit to determine if UART1 was connected - it was looking at the bit for UART0 so would always find a connection
based on a PR to Quark by …
> set up MOS for full-duplex comms

- main.c
- src/defines.h
boot sequence will now try to run `!Boot.obey`, followed by `autoexec.obey` and finally attempt to exec `autoexec.txt`
NB it is only the first one of these found that will be run.
additionally if being run with a VDP that supports the “check key” command, it will omit running the boot file if the shift key is held down
fixes #57 and #102
> update boot file checking

- src/mos.c
allows type to safely type out binary files
> make the type command escape its output

- src/mos.c
ensure that the command `*.` on alias resolution does not just match with first variable beginning with `Alias$`, as that prevents the internal `*.` from working
> fix alias resolution for *.

- src/keyboard.asm
The virtual keyboard does not handle the single quote key being pressed. This change fixes it.
> Fix virtual keyboard not detecting quote key

- main.c
- src/mos.c
- src/mos.h
- src/mos_api.asm
- src/mos_api.inc
- src/mos_sysvars.c
- src/version.h
Whilst APIs were added in MOS 3 alpha 2 to expose new underlying functionality, unfortunately some mistakes were made in their creation.  A notable flaw was the use of the `A` register as an API parameter - it isn't actually possible to use the `A` register as that is used to specify which API call is being made with `RST 8`.
This PR aims to address that by changing the APIs to use different registers.
There may also be a few enhancements too, such as the addition of a flag byte to the "unpack RTC" API to control whether/how an RTC refresh call will be made to the VDP.
Closes #122
> Changes and fixes to APIs introduced in MOS 3 alpha 2

- src/mos.c
- src/mos_api.asm
- src/mos_editor.c
- src/mos_editor.h
- src/mos_file.c
- src/mos_file.h
Enhancements to tab-completion, improving behaviour and fixing issues.
Cursor position on an auto-complete is now at the end of the inserted item, rather than at the end of the buffer.  This is more expected behaviour.
A tab-complete that matches a filename that includes a space will cause the filename to be wrapped in double-quotes, which fixes an issue with tab-completion of such filenames
Tab-complete for a term that begins with a double-quote will close the double-quotes if a match is found, whether or not the completed term includes a space.  the leading double-quote should be ignored when searching for matches
Tab-complete now omits/ignores hidden and system files, as those are not, by default, visible in directory listings
The `mos_resolvePath` API now accepts a flags byte in the B …
> Auto-complete enhancements

- main.c
- src/mos.c
- src/mos.h
Aliases, whether they are direct command aliases or load/run types, are now all handled in the same way, using a new `mos_execAlias` function.
This function will support multi-line aliases.
Command depth detection, which was used to detect infinite loops in command aliases, has been moved to use a global variable for the depth instead of an argument on the `mos_exec` function.  This means it can now also detect infinite loops in file load/run type aliases as well as command aliases, and also with the use of the `exec <scriptfile>` and `obey <obeyfile>` commands.  The maximum depth remains at 10.
> Add support for multi-line aliases

- src/mos.c
- src/mos_editor.c
- src/mos_file.c
- src/mos_file.h
- src/mos_sysvars.c
- src/mos_sysvars.h
the `resolvePath` function will now automatically perform variable expansion.  this behaviour can be prevented by setting a flag.  this means that the `mos_resolvepath` API will now by default perform variable expansion
the `getResolvedPath` function now accepts a `flags` byte which it passes thru to `resolvePath`.  this change allows us to remove the `expandPath`function
the `ifthere` command should now understand file paths that are wrapped in double-quotes
closes #146
> add support for variable expansion to resolvepath

- src/clock.c
- src/mos.c
- src/mos.h
- src/mos_api.asm
- src/mos_api.inc
- src/mos_editor.c
- src/mos_sysvars.h
- src/timer.c
- src/timer.h
mos_clearvdpflags (0x40) accepts a bitmask value of flags in the C register, clears those bits from the VDP protocol flags byte, and returns back the updated flags byte in the A register
mos_waitforvdpflags (0x41) accepts a bitmask value of flags in the C register, and will wait for those flags to all be set, or times out after roughly 1s.  it will return FR_OK or FR_TIMEOUT
> add two VDP protocol APIs

- src/misc.asm
- src/mos.c
- src/mos.h
- src/mos_api.asm
Work in progress...
adds a new utility call `FIX_HLU24` - other fatfs APIs will check MB for zero, and if it is then read the U byte from HLU and if it is clear sets to MB.  as this is common code this new utility call does that whole process in one step
this is used in the new ffs_api_fsync implementation
its use should be rolled out to other ffs_api_* calls that optionally set U of HLU to MB in this manner to save some bytes/complexity
> Add missing fatfs API calls

- src/mos.c
changes to how the `run` command in MOS 3 interprets its arguments introduced a bug that made it incompatible with commands written for MOS 1 and 2
the command `run . <filename>` should run the currently loaded program at the default address, passing in `<filename>` as the argument string.  instead the parser was seeing that `.` is not a number, and then passing the whole argument string
a side-effect of this is that `run <filename>` would work - but that behaviour is not desired, as ideally in the future that _should_ be equivalent to `runfile <filename>`
this update ensures that `run` now properly checks its arguments.  you must now either use no arguments, or provide a numeric address or a dot.
if the first argument is present but non-numeric an error will be reported - this differs …
> fix `run` command to be MOS 2 compatible

- src/mos.c
Command that can generate long output, specifically `dir`, `help` and `show`, will send a `VDU 23,0,&9A` to the VDP to enable temporary paged mode, if the VDP supports it
> enable “temporary paged mode” for some commands

- src/serial.asm
- src_startup/init_params_f92.asm
in `serial.asm` this changes a check inside the two `*_serial_TX` routines to check against the “TX hold register”.  this allows transmits to happen as soon as the serial system is no longer saying “hold”.  in benchmark testing this is is providing a very significant boost to our comms speed from MOS to the VDP, from around 640KBit/sec to 877KBit/sec.  as this is a measure of data bits sent, and our comms config sents 1 stop-bit per byte, this is getting very close to the maximum theoretical data rate
also changes the `FLASH_CTRL` configuration to use a value of `0x08`, which sets ROM/flash memory access to zero wait-states..  this boosts the perfomance of calling MOS APIs by around 17% (I could not see how to adjust the `__FLASH_CTL_INIT_PARAM` setting - this does not appear to be a …
> speed boosts

- src/mos_api.asm
- src/mos_api.inc
- src/sd.h
adds in four APIs, `sd_getunlockcode`, `sd_init`, `sd_readblocks` and `sd_writeblocks`
these provide low-level access to the SD card, and are simple wrappers over the underlying functions that FatFS uses for disk access (as used inside `diskio.c`)
to guard against accidental usage of these APIs, programs must use `sd_getunlockcode` and then provide that unlock code when calling `sd_init`, `sd_readblocks` and `sd_writeblocks`
> add APIs for low-level SD card access

- src/mos.c
- src/mos_api.asm
- src/mos_api.inc
- src/mos_editor.c
- src/mos_file.c
- src/mos_file.h
- src/mos_sysvars.c
- src/mos_sysvars.h
- src/tests.c
this function returns a pointer to a function.  in general these should be functions that follow the C calling convention, and will be used to expose raw C functions
parameters are:
C = flags (must be zero for now)
B = function number
returns:
A = status (0, 19 or 20)
HL = pointer to function, or 0 if invalid
for now exposes the SD card C functions, and also `f_printf` which we can’t easily expose as a MOS-style API, as well as some other functions that use the IX register and so are awkward to call from C
flags are included for future use.  this may in the future allow a way to go beyond 256 functions, or if/when we introduce MOS modules control whether functions from modules will be returned or not
when called from Z80 mode, will return 20 (invalid command) as you can’t use these …
> add a mos_getfunction API (0x50)

- README.md
- src/mos.h
- src/mos_api.asm
- src/version.h
fixes an issue where the new `mos_escapestring` wasn't returning the calculated length result
also includes edits to reflect that this is now Agon Platform MOS
> fix mos_escapestring, and edits to change to Agon Platform MOS

- src/mos.c
- src/mos.h
as some folks found the auto-paging behaviour of MOS confusing this PR makes that functionality opt-in.
setting the system variable `CLI$AutoPaged` to any value enables the functionality.  by default this variable is not set.  any star command that supports auto-paging will be paged if this variable is set, meaning this will also happen when the command is executed via `mos_oscli` - it is the MOS command line interpreter that has this functionality, not the interactive command line.
turning on auto-paged output has been refactored into a function called `autoPageOutput()`
the `*type` command now also uses auto-paging, as that was an obvious omission
Fixes #175
> changes to MOS CLI's auto-paging support for various commands
